# Generated by Django 4.0.6 on 2026-05-12 13:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(help_text='Número de identificación tributaria', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='NIT')),
                ('razon_social', models.CharField(help_text='Nombre legal de la empresa', max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre de fantasía o marca', max_length=200, null=True, verbose_name='Nombre Comercial')),
                ('direccion_fiscal', models.TextField(help_text='Dirección registrada ante la SAT', verbose_name='Dirección Fiscal')),
                ('direccion_comercial', models.TextField(blank=True, help_text='Dirección de operaciones (opcional)', null=True, verbose_name='Dirección Comercial')),
                ('propietario', models.CharField(help_text='Nombre del propietario o representante legal', max_length=200, verbose_name='Propietario/Representante')),
                ('es_sociedad', models.BooleanField(default=False, help_text='Marque si es una sociedad anónima o colectiva', verbose_name='¿Es Sociedad?')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento de la licencia/contrato', verbose_name='Fecha de Vencimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
