# Generated by Django 4.0.6 on 2026-05-13 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0002_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaContable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Área Contable')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Área Contable')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Área Contable',
                'verbose_name_plural': 'Áreas Contables',
                'ordering': ['nombre'],
            },
        ),
    ]
