# Generated by Django 4.0.6 on 2026-05-13 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0004_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del grupo contable', max_length=200, unique=True, verbose_name='Nombre del Grupo')),
                ('tipo_movimiento', models.IntegerField(default=1, editable=False, verbose_name='Tipo de Movimiento')),
                ('orden', models.IntegerField(default=1, editable=False, verbose_name='Orden')),
                ('numero_nomenclatura', models.IntegerField(default=1, editable=False, verbose_name='Número de Nomenclatura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('id_area_contable', models.ForeignKey(help_text='Seleccione el área contable asociada', on_delete=django.db.models.deletion.PROTECT, to='administracion.areacontable', verbose_name='Área Contable')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Nomenclatura - Grupo',
                'verbose_name_plural': 'Nomenclatura - Grupos',
                'ordering': ['nombre'],
            },
        ),
    ]
