# Generated by Django 4.0.6 on 2026-05-13 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0005_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del subgrupo contable', max_length=200, verbose_name='Nombre del SubGrupo')),
                ('tipo_movimiento', models.IntegerField(default=1, editable=False, verbose_name='Tipo de Movimiento')),
                ('orden', models.IntegerField(default=1, editable=False, verbose_name='Orden')),
                ('numero_nomenclatura', models.IntegerField(default=1, editable=False, verbose_name='Número de Nomenclatura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgrupos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('id_area_contable', models.ForeignKey(help_text='Área contable asociada', on_delete=django.db.models.deletion.PROTECT, to='administracion.areacontable', verbose_name='Área Contable')),
                ('id_grupo', models.ForeignKey(help_text='Grupo al que pertenece este subgrupo', on_delete=django.db.models.deletion.PROTECT, to='administracion.grupo', verbose_name='Grupo')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgrupos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'SubGrupo',
                'verbose_name_plural': 'SubGrupos',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'id_grupo')},
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la cuenta contable', max_length=200, verbose_name='Nombre de la Cuenta')),
                ('orden', models.IntegerField(default=1, editable=False, verbose_name='Orden')),
                ('tipo_movimiento', models.IntegerField(default=1, editable=False, verbose_name='Tipo de Movimiento')),
                ('numero_nomenclatura', models.IntegerField(default=1, editable=False, verbose_name='Número de Nomenclatura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('id_area_contable', models.ForeignKey(help_text='Área contable asociada', on_delete=django.db.models.deletion.PROTECT, to='administracion.areacontable', verbose_name='Área Contable')),
                ('id_subgrupo', models.ForeignKey(help_text='Subgrupo al que pertenece esta cuenta', on_delete=django.db.models.deletion.PROTECT, to='administracion.subgrupo', verbose_name='SubGrupo')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'id_subgrupo')},
            },
        ),
    ]
