# Generated by Django 4.0.6 on 2026-05-13 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0006_subgrupo_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(help_text='Nombre comercial de la sucursal', max_length=200, verbose_name='Nombre Comercial')),
                ('nit', models.CharField(help_text='Número de identificación tributaria de la sucursal', max_length=20, verbose_name='NIT')),
                ('establecimiento', models.CharField(help_text='Nombre o código del establecimiento', max_length=200, verbose_name='Establecimiento')),
                ('direccion', models.CharField(help_text='Dirección física de la sucursal', max_length=200, verbose_name='Dirección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('id_empresa', models.ForeignKey(help_text='Empresa a la que pertenece esta sucursal', on_delete=django.db.models.deletion.PROTECT, to='administracion.empresa', verbose_name='Empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre_comercial'],
                'unique_together': {('id_empresa', 'nombre_comercial')},
            },
        ),
    ]
