# Generated by Django 4.0.6 on 2026-05-13 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0007_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.BooleanField(default=False, help_text='Indica si este es el período predeterminado de la empresa', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_periodos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('id_empresa', models.ForeignKey(help_text='Empresa asociada', on_delete=django.db.models.deletion.PROTECT, to='administracion.empresa', verbose_name='Empresa')),
                ('id_periodo', models.ForeignKey(help_text='Período contable asignado a la empresa', on_delete=django.db.models.deletion.PROTECT, to='administracion.periodo', verbose_name='Período')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_periodos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Período de Empresa',
                'verbose_name_plural': 'Períodos de Empresas',
                'ordering': ['-id_periodo__fecha_inicial'],
                'unique_together': {('id_empresa', 'id_periodo')},
            },
        ),
    ]
