# Generated by Django 4.0.6 on 2026-05-25 03:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0008_empresaperiodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('estatus', models.IntegerField(choices=[(0, 'Borrador'), (1, 'Finalizado')], default=0, verbose_name='Estatus')),
                ('correlativo', models.IntegerField(blank=True, null=True, verbose_name='Correlativo')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('mes', models.IntegerField(blank=True, null=True, verbose_name='Mes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_creados', to=settings.AUTH_USER_MODEL)),
                ('id_empresa_periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='administracion.empresaperiodo', verbose_name='Período de Empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['-fecha', '-correlativo'],
                'unique_together': {('id_empresa_periodo', 'correlativo')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto')),
                ('tipo_movimiento', models.IntegerField(choices=[(1, 'Debe'), (2, 'Haber')], verbose_name='Tipo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('id_asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='administracion.asiento', verbose_name='Asiento')),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.cuenta', verbose_name='Cuenta')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre/Proveedor')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_creados', to=settings.AUTH_USER_MODEL)),
                ('id_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='administracion.movimiento', verbose_name='Movimiento')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento',
                'verbose_name_plural': 'Detalles de Movimientos',
            },
        ),
        migrations.CreateModel(
            name='CorrelativoAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('ultimo_correlativo', models.IntegerField(default=0, verbose_name='Último Correlativo')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Correlativo de Asiento',
                'verbose_name_plural': 'Correlativos de Asientos',
                'unique_together': {('id_empresa', 'anio', 'mes')},
            },
        ),
    ]
