# Generated by Django 4.0.6 on 2026-06-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_asiento_movimiento_detallemovimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento de la licencia/contrato', null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
