# Generated by Django 4.0.6 on 2026-06-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_alter_empresa_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimiento',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción adicional del detalle', max_length=500, null=True, verbose_name='Descripción'),
        ),
    ]
