# Generated by Django 4.0.6 on 2026-06-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_detallemovimiento_descripcion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('id_empresa_periodo', 'anio', 'mes', 'correlativo')},
        ),
    ]
