# Generated by Django 4.0.6 on 2026-06-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_alter_asiento_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together=set(),
        ),
    ]
