# Generated by Django 4.0.6 on 2026-06-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_alter_asiento_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre/Proveedor'),
        ),
    ]
