# Generated by Django 4.0.6 on 2026-06-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_alter_detallemovimiento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='folio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Folio'),
        ),
    ]
